// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgres://6204c14d07903ee394a4a6eaa9ac663dad233fdfc6dd1ee5b20431ce18bc1928:sk_daTQ17zwz0kElUZiAZ1k_@db.prisma.io:5432/postgres?sslmode=require"],
  },
});
